### ISSUE TITLE
So, iOS support is coming back?

### ISSUE THREAD

**Issue by ThaDaVos** [pwa-builder/pwabuilder-ios#1]
So, iOS support is coming back to PWABuilder?

**Comment by JudahGabriel** [comment]
We've got some things in the works. We'll have more to announce soon.

**Comment by ThaDaVos** [comment]
Great! We currently have an App in the App Store using the old generated template but it's really getting outdated, hard to update and we're having a few little issues - so if there's a new and better way to bundle one I would love to try it out (can you spoiler a little on what will be used? Cordova, something else?)

**Comment by ThaDaVos** [comment]
Anything @JudahGabriel ?

**Comment by JudahGabriel** [comment]
We'll announce it on the [PWABuilder blog](https://blog.pwabuilder.com) when it's ready.

**Comment by JudahGabriel** [comment]
[Released](https://blog.pwabuilder.com/posts/publish-your-pwa-to-the-ios-app-store/)! 😊
