### ISSUE TITLE
PWA refreshes on opening youtube Videos and clicking "done"

### ISSUE THREAD

**Issue by MrVibe** [pwa-builder/pwabuilder-ios#13]
First of all Kudos on the awesome job ! iOS for PWA this is going to change a lot of things.

I am facing a minor issue in my PWA. When my PWA has an embedded Youtube Videos or an iframe embed. There is a "Done" label on top left label. The entire screen seems to be overlapped by this done label and on clicking it, the PWA refreshes. Can i remove this "Done" label ?

I already added the youtube.com & other iframe sources as external links of the PWA configuration at the time of importing ios pack for the PWA.

See video :

https://drive.google.com/file/d/15y4WoQXzwxPZmOxdCxWUzcUCczClFi06/view?usp=drivesdk

**Comment by khmyznikov** [comment]
The "Done" bar is made for external redirect-authentication resources when you change the main URL, it allows you to return back if something goes wrong there. What happens if you remove youtube from the domains list?

**Comment by MrVibe** [comment]
Yes, if you remove youtube from the list the screen simply refreshes and the PWA loads again.

somehow the firebase powered social logins are also not working, even though I added the firebase app link in the authOrigins.

this is what shows up in settings.swift ,
`let authOrigins: [String] = ["youtube.com","vimeo.com","appwplmsio.firebaseapp.com","account.google.com","facebook.com","live.com"]
`

**Comment by MrVibe** [comment]
Another question, I am using firebase for web in the App, do I need to configure it again for the iOS app ? becuase i see this warning message in xcode debug as well 

_[Firebase/Core][I-COR000003] The default Firebase app has not yet been configured. Add `FirebaseApp.configure()` to your application initialization. This can be done in in the App Delegate's application(_:didFinishLaunchingWithOptions:)` (or the `@main` struct's initializer in SwiftUI). Read more: https://goo.gl/ctyzm8_

**Comment by khmyznikov** [comment]
@JudahGabriel so we need to add another list of domains like "resourceOrigins" something like that and do not call "Done" logic for it.
@MrVibe You should understand what you can't use more than 10 bound domains, so choose them consciously. Social logins can use multiple domains in a row, multiple redirects, and you pretty soon can be limited by 10 domains allowed. You should add every domain in the login chain to bound domains.

**Comment by khmyznikov** [comment]
> Another question, I am using firebase for web in the App, do I need to configure it again for the iOS app ? becuase i see this warning message in xcode debug as well
> 
> _[Firebase/Core][I-COR000003] The default Firebase app has not yet been configured. Add `FirebaseApp.configure()` to your application initialization. This can be done in in the App Delegate's application(_:didFinishLaunchingWithOptions:)`(or the`@main` struct's initializer in SwiftUI). Read more: https://goo.gl/ctyzm8_

If you don't use pushes, you don't need firebase.

**Comment by MrVibe** [comment]
yes thank you, firebase issue is resolved, I had to enter the full firebase app url. 

Yes, done logic is not required for Videos etc.

**Comment by khmyznikov** [comment]
@MrVibe do you fix this? I have created a test page with an iframe youtube video and I have no problem with it...

**Comment by MrVibe** [comment]
Yes, I was able to fix this. I had to add some domains in the xCode project and finally our ios App is live. Thank you PWAbuilder .
https://apps.apple.com/us/developer/vibethemes/id1321300155
