### ISSUE TITLE
icon not maksed properly

### ISSUE THREAD

**Issue by tavelli** [pwa-builder/pwabuilder-ios#15]
icon doesn't seem to be generated properly for iOS App Store

**To Reproduce**
1. Build an app and download iOS app store package
2. Open in simulator

**Expected behavior**
Icon is generated with appropriate cropping for iOS, or some note in documentation on how to provide proper icons for iOS App Store

**Screenshots**
![Screen Shot 2021-10-30 at 5 19 55 PM](https://user-images.githubusercontent.com/484951/139558691-c4c9d0f1-bf86-42f8-b86c-70aa1f38e241.png)

**Additional info (please complete the following information):**

Testing in simulator
iPhone 13
iOS 15.0

manifest setup for icons

```
"icons": [
    {
      "src": "/images/icon-192.png?v=52d2f2302eeccc63721d723138c758ed",
      "sizes": "192x192",
      "type": "image/png"
    },
    {
      "src": "/images/icon-512.png?v=52d2f2302eeccc63721d723138c758ed",
      "sizes": "512x512",
      "type": "image/png"
    },
    {
      "src": "/images/maskable_icon-192.png?v=52d2f2302eeccc63721d723138c758ed",
      "sizes": "192x192",
      "type": "image/png",
      "purpose": "maskable"
    },
    {
      "src": "/images/maskable_icon-512.png?v=52d2f2302eeccc63721d723138c758ed",
      "sizes": "512x512",
      "type": "image/png",
      "purpose": "maskable"
    }
  ],
```

**Comment by wojtekmaj** [comment]
I'm also seeing this issue, although in my case `"purpose"` was set to `"any maskable"` and I thought that this may be an issue - it seems like not.

**Comment by justrealmilk** [comment]
Same issue here.

**Comment by JudahGabriel** [comment]
Fixed! Please repackage with PWABuilder and you'll be all set.

**Comment by wojtekmaj** [comment]
Confirmed fixed! Thanks!

**Comment by tavelli** [comment]
thanks!
