### ISSUE TITLE
All links open in new window

### ISSUE THREAD

**Issue by goaround** [pwa-builder/pwabuilder-ios#16]
Hi,

Awesome to have the option to publish to the Apple App Store!

I tried my App in the simulator, but every link on my homepage opens as it would be on a separated domain in a new window (with the *Done* button)

I tried to add my domain to  *Permitted URLs* but then even the homepage has the *Done* button.

Any idea? Where can I check the permitted urls in Xcode?

**Comment by khmyznikov** [comment]
It's the same domain like the main? How do your links look like?

**Comment by khmyznikov** [comment]
Good. Yep in origins should be domains only.

**Comment by justrealmilk** [comment]
Just ran into the exact same issue. Was this something that I caused or the builder frontend? It's the same as `rootUrl` sans protocol
