### ISSUE TITLE
Display web view full screen, define safe-area-inset-*?

### ISSUE THREAD

**Issue by wojtekmaj** [pwa-builder/pwabuilder-ios#17]
It looks like at the moment, WKWebView leaves space for the status bar, and leaves no space at the bottom for the nav bar.

<img width="426" alt="Zrzut ekranu 2021-11-1 o 22 46 49" src="https://user-images.githubusercontent.com/5426427/139746439-4883b20a-b97a-4b6f-86d0-53ffe564d278.png">

Now, this is really 2 issues for the price of one:

### Space left for the status bar

This avoids an issue where most navigation elements usually sit at the top and could be covered by the status bar if not accounted for correctly. So, I get why this could be a default behavior. 

But if I were able to set WKWebView to full screen, I would be able to create much better looking apps. Just look at the screenshot above - I think you'd agree with me it would look much nicer if the map was spanning all the way to the top.

### No space at the bottom for the nav bar

Lack of space is a much bigger problem than some extra space. My app uses `padding-bottom: env(safe-area-inset-bottom)` to avoid menu collision with unsafe area of the screen. This came in especially handy on early iOS 15 betas with the floating nav bar. On WKWebView tough, it seems like these env values are all set to 0, so the app menu sits awkwardly close to the bottom edge.

**Comment by khmyznikov** [comment]
Yeah, this definitely needs to be improved, stay tuned for future versions.

**Comment by khmyznikov** [comment]
@wojtekmaj do you set `<meta name="viewport" content="viewport-fit=cover" />`? Looks like it should work even in current version, at least for bottom spacing.
![Screenshot 2021-11-06 at 15 26 20](https://user-images.githubusercontent.com/6115884/140609568-9308c72a-7144-4258-a119-c220a717992e.png)

**Comment by wojtekmaj** [comment]
Thanks for your answer @khmyznikov!

This does change things quite a bit, but not quite as I imagined. **It does change the layout by getting rid of white bars horizontally, but not vertically.** 

There are other problems seen on this screen; a different media query kicked in so the difference in horizontal is slightly more than the absence of white bars, and it seems like in this mode Safari suddenly sets value for `env(safe-area-inset-bottom)`, resulting in, in my specific case, duplicated padding.

Have a look:

|                      | Before | After
|---|---|---|
| Vertical     |  <img width="300" alt="simulator_screenshot_5377C5DD-458D-491D-9646-2EC0D4FAC327" src="https://user-images.githubusercontent.com/5426427/140621505-9dca761c-38c0-4f8c-b947-a54f9cbfa44d.png" /> | <img width="300" alt="simulator_screenshot_9E888F22-662D-48F5-8DFC-72523DD66AF7" src="https://user-images.githubusercontent.com/5426427/140621483-b718649b-2fa1-4d39-bd78-4700ca104105.png" />
| Horizontal | ![simulator_screenshot_028CB34F-1FFF-4D3E-8F20-601C7DA9086F](https://user-images.githubusercontent.com/5426427/140621519-3c8e5f9f-a04d-4157-b2d1-7fc0131ae93c.png) |  ![simulator_screenshot_4E421DF3-58EA-40AC-AA23-2ABA7B9F38A8](https://user-images.githubusercontent.com/5426427/140621452-4d8dc025-bcc2-4ad6-87b1-ffbdf00f1949.png)

**Comment by khmyznikov** [comment]
Maybe I will push a commit tomorrow and you can take a look It's getting better or not.

**Comment by khmyznikov** [comment]
Please try this commit @wojtekmaj https://github.com/pwa-builder/pwabuilder-ios/pull/14/commits/dca4067c00ab7ea27acf0b2b368ca547a2c90ef3

**Comment by wojtekmaj** [comment]
@khmyznikov Wow! That works _beautifully_! Of course I had to change `displayMode` to `"fullscreen"` but after that it looks like a dream! Thanks!

<img alt="Zrzut ekranu 2021-11-10 o 10 44 13" width="300" src="https://user-images.githubusercontent.com/5426427/141089535-d7650931-a10c-4f9b-8d84-e8e73d3df7b2.png" />

<img alt="Zrzut ekranu 2021-11-10 o 10 44 38" width="600" src="https://user-images.githubusercontent.com/5426427/141089595-d73533b4-6bf0-4040-847d-892f5e18d9bc.png" />

**Comment by wojtekmaj** [comment]
Kind of a duplicate of #8 now that I think about it
