### ISSUE TITLE
Altering statusBarColor after package generation

### ISSUE THREAD

**Issue by justrealmilk** [pwa-builder/pwabuilder-ios#21]
Hi! So like a dummy I didn't change statusBarColor from #FFFFFF... I searched the workspace for statusBarColor and there were 3 references but in each case the code that mentions it is commented out sooo I don't know where the setting is hiding

<img width="563" alt="Screen Shot 2021-11-04 at 1 25 33 pm" src="https://user-images.githubusercontent.com/156681/140253317-c025659e-9ea1-41ff-8a2a-31465b569dcb.png">

**Comment by khmyznikov** [comment]
@justrealmilk
![Screenshot 2021-11-05 at 11 53 50](https://user-images.githubusercontent.com/6115884/140484237-4408ac61-dff3-49a8-8f59-8c7779a0d8b7.jpg)
Try to adjust this options.

**Comment by justrealmilk** [comment]
Perfect! Just needed to set `Background` on `Webview View` to `Default` from `Custom` (which was set to white)

Thanks
