### ISSUE TITLE
LaunchScreen and App icons

### ISSUE THREAD

**Issue by justrealmilk** [pwa-builder/pwabuilder-ios#22]
As far as I can tell, icons are in no way set programmatically, right? I've successfully altered the icon for the Main storyboard but LaunchScreen is still stuck (provided LaunchScreen is the first screen)... 

| App icon masking issue as per #15 | LaunchScreen icon incorrect |
| --- | --- |
| <img width="563" alt="Screen Shot 2021-11-05 at 9 25 52 pm" src="https://user-images.githubusercontent.com/156681/140504111-5072d91b-1254-4c0e-8ebb-474bc066b773.png"> | <img width="563" alt="Screen Shot 2021-11-05 at 9 26 26 pm" src="https://user-images.githubusercontent.com/156681/140504105-56db41e6-c57c-48d0-bcb6-0e79cc7adada.png"> |

| LaunchScreen storyboard | Main Storyboard |
| --- | --- |
| <img width="1707" alt="Screen Shot 2021-11-05 at 9 25 06 pm" src="https://user-images.githubusercontent.com/156681/140504118-d2f1ced6-458e-4338-9fff-08d08923effa.png"> | <img width="1707" alt="Screen Shot 2021-11-05 at 9 25 19 pm" src="https://user-images.githubusercontent.com/156681/140504116-1e1232b2-cb90-4a9a-968e-1beb6f7c836f.png"> |

Assets

<img width="1707" alt="Screen Shot 2021-11-05 at 9 25 41 pm" src="https://user-images.githubusercontent.com/156681/140504113-122e1f28-c038-4daa-9aad-7f784dd1f216.png">

`LaunchIcon` is a single asset with a universal size.

**Comment by khmyznikov** [comment]
Same issue #15.
Currently yes icons generating a bit not right, I'm sure in the next versions this will be fixed.
For now, please [try this tool](https://apps.apple.com/us/app/icon-set-studio/id1501296766), it helps you generate icons manually and you can replace broken ones in Assets.

**Comment by justrealmilk** [comment]
> Same issue #15.
> 
> Currently yes icons generating a bit not right, I'm sure in the next versions this will be fixed.
> 
> For now, please [try this tool](https://apps.apple.com/us/app/icon-set-studio/id1501296766), it helps you generate icons manually and you can replace broken ones in Assets.

I mentioned #15 myself but as I also said, after checking the assets and comparing to other projects, I can't find any issue
