### ISSUE TITLE
Use LF, not CRLF, for generating files

### ISSUE THREAD

**Issue by wojtekmaj** [pwa-builder/pwabuilder-ios#24]
When Xcode saves files after they are edited, it saves them with LF by default, not CRLF used by PWA Builder, which creates HUGE diffs despite, in fact, tiny changes in the actual file structure. This specially applies to *.Storyboard, *.plist files.

**Comment by JudahGabriel** [comment]
I've got a pending PR that changes the iOS project files endings to LF, and defaults to the same. Thanks! Should be fixed and committed this week.
