### ISSUE TITLE
Add ITSAppUsesNonExemptEncryption to info.plist

### ISSUE THREAD

**Issue by david-buck** [pwa-builder/pwabuilder-ios#33]
Small enhancement but can potentially speed up the submission process

https://developer.apple.com/documentation/bundleresources/information_property_list/itsappusesnonexemptencryption

**Comment by JudahGabriel** [comment]
So, we'd set that value to `No`, correct? (Assuming HTTPS usage is exempt.)

**Comment by david-buck** [comment]
That is correct. Default to `No`.

**Comment by JudahGabriel** [comment]
Done, I've added this to setting to Info.plist. Thanks @david-buck !
