### ISSUE TITLE
Universal links aren't being handled by wkwebview

### ISSUE THREAD

**Issue by david-buck** [pwa-builder/pwabuilder-ios#34]
My app has both `applinks:` and `webcredentials:`  set in `com.apple.developer.associated-domains` in `com.apple.developer.associated-domains` in the `Entitlements.plist` file

My domain has `.well-known/apple-app-site-association` set up like this

```{
  "applinks": {
    "apps": [],
    "details": [
      {
        "appID": "APPID",
        "paths": [
          "*"
        ]
      }
    ]
  }
} 
```

On both the simulator and on a real device (Testflight), any links to my domain will open the app but will open on the last view that was loaded in the app - the same as tapping on the app's icon would.

I am not well versed in iOS development, so my attempts to add breakpoints and `print()`s to the AppDelegate file have returned nothing.

**Comment by khmyznikov** [comment]
Yep, it's not implemented yet.

**Comment by david-buck** [comment]
I've solved this in my project by moving the universal link handling code into the SceneDelegate.swift file and commenting out most of the remainder of AppDelegate. 

Remaining code:


AppDelegate.swift
```
import UIKit

@UIApplicationMain

class AppDelegate: UIResponder, UIApplicationDelegate {
    
    var window : UIWindow?

}
```

SceneDelegate.swift
```
import UIKit

@available(iOS 13.0, *)
class SceneDelegate: UIResponder, UIWindowSceneDelegate {
    
    var window: UIWindow?
    
    func scene(_ scene: UIScene, continue userActivity: NSUserActivity) {

        guard userActivity.activityType == NSUserActivityTypeBrowsingWeb,
              let incomingURL = userActivity.webpageURL else {
                  return
              }

        // Handle it inside our web view.
        let handledRequest = URLRequest(url: incomingURL)
        Catchy.webView.load(handledRequest)
        return
    } 
}
```

**Comment by JudahGabriel** [comment]
Thanks! Let me experiment with this and see if I can make the same changes for the iOS template. Thanks @david-buck!

**Comment by JudahGabriel** [comment]
Sure enough, just moving the universal links handler from AppDelegate to SceneDelegate fixed the issue. I'm doing a PR to merge this into the PWABuilder iOS template. Thanks @david-buck !

**Comment by JudahGabriel** [comment]
Fixed. I'll have this deployed to production shortly.
