### ISSUE TITLE
Starting URLs with an ampersand generate faulty Info.plist

### ISSUE THREAD

**Issue by tlhunter** [pwa-builder/pwabuilder-ios#36]
I created an app with PWA Builder using the following starting URL:

```
https://example.org/?app&platform=ios
```

This generated an Info.plist file for Xcode that had an unescaped `&` character in it and Xcode would refuse to generate the project. By encoding the ampersand as `&amp;` the product was then able to build.

**Comment by tlhunter** [comment]
I'm curious if this has any side effects of the `allowedOrigin` variable in `Settings.swift`? I manually changed that value to `example.org`, deleting the path and query, to be safe.

**Comment by JudahGabriel** [comment]
Thanks for reporting this. Fixed.

> I'm curious if this has any side effects of the allowedOrigin variable in Settings.swift? I manually changed that value to example.org, deleting the path and query, to be safe.

Seems to be OK. Just tried it out by having the path and query in allowed origin, works as expected.

**Comment by JudahGabriel** [comment]
Update: the query string was indeed interfereing with the location.reload issue you reported in another thread.

Both of these issues have been fixed. You can use query strings in your URL if you wish; location.reload() will work as expected.
