### ISSUE TITLE
How to remove navbar from the iOS PWA?

### ISSUE THREAD

**Issue by shikata-ga-nai** [pwa-builder/pwabuilder-ios#42]
I've built PWA for iOS (15.3) per instructions on the pwabuilder website, everything works okay, however there's a Navigation Bar with "Done" button stuck all the time at the top of the page (screenshot attached)
![147826892-8243e004-c003-4064-aa08-32b361b36960](https://user-images.githubusercontent.com/2530893/147829687-e4311249-5e7b-4272-8670-94d7f5db8963.jpg)
The URL of the PWA I'm trying to build is app.kash.io. Any suggestions on how to remove it?

**Comment by JudahGabriel** [comment]
What URL did you use in PWABuilder? And are you redirecting to a different URL?

The "Done" bar shows when the web address isn't on the same domain host you used in PWABuilder.

**Comment by JudahGabriel** [comment]
Another possibility: did you specify a query string when creating your package in PWABuilder? We just deployed a fix for that yesterday, but if you included a query string in your URL, it would show the "done" bar, thinking it an external navigation.

This has been fixed, and just requires you to regenerate your iOS package in PWABuilder.

**Comment by JudahGabriel** [comment]
Closing this question as you asked it in the main PWABuilder repo. https://github.com/pwa-builder/PWABuilder/issues/2350
