### ISSUE TITLE
Error: `zsh: abort      pod install`

### ISSUE THREAD

**Issue by mariushoppe** [pwa-builder/pwabuilder-ios#43]
I tried to make an iOS App using PWABuilder, but I fail at `pod install`.
Error: `zsh: abort      pod install`
I tried `sudo gem install cocoapods` before but it didn't worked either.

Any ideas?

I run Xcode on a new MacBook Pro with M1 Max.

**Comment by vitaliidasaev** [comment]
cocoapods problems 
https://developer.apple.com/forums/thread/668456
I solved this problem with using brew
You need to:
 1 install LATEST version of brew (https://treehouse.github.io/installation-guides/mac/homebrew)
 2 then use "brew uninstall cocoapods"
 3 install the latest version of cocoapods using "brew install cocoapods" (You must verify installed version with github version https://github.com/CocoaPods/CocoaPods/releases/tag/1.11.2, they must match)
 4 overwrite link to cocoapods with "brew link --overwrite cocoapods"
 5 check the version of cocoapods "pod --version"
 6 done, You have the latest version of cocoapods installed

**Comment by mariushoppe** [comment]
It works! Thank you so much!
